apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: aflu/ascent-notification:latest
          ports:
            - containerPort: 3003
          env:
            - name: NOTIFICATION_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: NOTIFICATION_SERVICE_PORT
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: KAFKA_BROKER_URL
            - name: KAFKA_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: KAFKA_USER_NAME
            - name: KAFKA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: KAFKA_PASSWORD
            - name: AUTH_SERVICE_KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: AUTH_SERVICE_KAFKA_GROUP_ID
            - name: USER_SERVICE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: USER_SERVICE_TOPIC
            - name: NOTIFICATION_SERVICE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: NOTIFICATION_SERVICE_TOPIC
            - name: NOTIFICATION_SERVICE_KAFKA_CONSUMER_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: NOTIFICATION_SERVICE_KAFKA_CONSUMER_GROUP_ID
            - name: NOTIFIICATION_SERVICE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: NOTIFIICATION_SERVICE_TOPIC
            - name: AUTH_SERVICE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: AUTH_SERVICE_TOPIC
            - name: ASCENT_OFFICIAL_MAIL
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: ASCENT_OFFICIAL_MAIL
            - name: ASCENT_SECRET_PASS
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: ASCENT_SECRET_PASS
            - name: JWT_EMAIL_VALIDATION_KEY
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: JWT_EMAIL_VALIDATION_KEY
