name: ascent-job

on:
  push:
    branches:
      - main
    paths:
      - 'services/job/**'
  pull_request:
    branches:
      - main
    paths:
      - 'services/job/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./services/job
          push: true
          tags: aflu/ascent-job:latest